modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"
[[mods]]
modId="templatemod"
version="0.0.1-1.19.2"
displayName="Template Mod"
authors="zzzaitegui"
description='''A Forge 1.19.2 template mod.'''
[[dependencies.templatemod]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.templatemod]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.templatemod]]
modId="geckolib3"
mandatory=true
versionRange="[3.1.40,)"
ordering="NONE"
side="BOTH"
