modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="bsf"
version="1.0.3-1.21.1"
mixinConfigs = ["bsf.mixins.json"]
displayName="Better Snowy Features"
logoFile="bsf_logo.png"
authors="zzzaitegui"
description='''
Adds snowy textures to trees and plants in cold biomes, plus icicles and always snowy grass blocks for a cohesive winter look.
'''

[[dependencies.bsf]]
modId="forge"
mandatory=true
versionRange="[52.1.6,)"
ordering="NONE"
side="BOTH"

[[dependencies.bsf]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"