modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
# logoFile="logo.png" # NO LOGO YET

[[mods]]
modId="modgov"
version="1.0.2-1.20.1"
displayName="Mod.gov"
# logoFile="logo.png" # NO LOGO YET
authors="zzzaitegui"
description='''
A comprehensive elections and voting mod for Minecraft 1.20.1 roleplay servers.
Features political party registration, elections, voting system, ID cards, and pamphlets for creating basic democratic gameplay.
'''

[[dependencies.modgov]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.modgov]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"